[package]
name = "keyforge95"
description = "Library for product key generation / validation for Windows 95 and other Microsoft products"
authors = ["Nando Lawson"]
version = "2.2.0"
categories = ["algorithms", "development-tools"]
keywords = ["windows", "product", "key", "generator", "validator"]
readme = "README.md"
license = "GPL-3.0"
exclude = ["target/", ".github/", ".gitignore"]
repository = "https://github.com/nandolawson/keyforge95"
edition = "2021"

[dependencies]
rand = "0.8.5"

[lib]
crate-type = ["rlib", "cdylib"]
doc = true
doctest = true
harness = true
proc-macro = false
test = true

[lints.clippy]
cargo = "deny"
complexity = "deny"
correctness = "deny"
pedantic = "deny"
perf = "deny"
restriction = "allow"
style = "deny"
suspicious = "deny"

[profile.dev]
codegen-units = 256
debug = true
incremental = true
lto = false
opt-level = 0
panic = "unwind"
strip = false

[profile.release]
codegen-units = 1
debug = "none"
incremental = true
lto = true
opt-level = 3
panic = "abort"
strip = true

[target.'cfg(wasm32)'.dependencies]
getrandom = "0.2.15"
wasm-bindgen = { version = "0.2.93", default-features = false }
